language: node_js
node_js: stable
script:
  - cd music && yarn install --ignore-scripts
  - yarn lint && yarn test && yarn build
  - cd ../sketch && yarn install --ignore-scripts
  - yarn lint && yarn build
  - cd ../image && yarn install --ignore-scripts
  - yarn lint && yarn build
