export declare const DEFAULT_QUARTERS_PER_MINUTE = 120;
export declare const DEFAULT_STEPS_PER_BAR = 16;
export declare const DEFAULT_STEPS_PER_QUARTER = 4;
export declare const DEFAULT_STEPS_PER_SECOND = 100;
export declare const DEFAULT_VELOCITY = 80;
export declare const DEFAULT_PROGRAM = 0;
export declare const DEFAULT_TICKS_PER_QUARTER = 220;
export declare const DEFAULT_CHANNEL = 0;
export declare const DRUM_CHANNEL = 9;
export declare const NON_DRUM_CHANNELS: ReadonlyArray<number>;
export declare const DEFAULT_DRUM_PITCH_CLASSES: number[][];
export declare const MIN_MIDI_VELOCITY = 0;
export declare const MAX_MIDI_VELOCITY = 127;
export declare const MIDI_VELOCITIES: number;
export declare const NO_CHORD = "N.C.";
export declare const NUM_PITCH_CLASSES = 12;
export declare const MIN_MIDI_PITCH = 0;
export declare const MAX_MIDI_PITCH = 127;
export declare const MIDI_PITCHES: number;
export declare const MIN_PIANO_PITCH = 21;
export declare const MAX_PIANO_PITCH = 108;
export declare const MIN_DRUM_PITCH = 35;
export declare const MAX_DRUM_PITCH = 81;
export declare const MIN_MIDI_PROGRAM = 0;
export declare const MAX_MIDI_PROGRAM = 127;
export declare const LO_CLICK_PITCH = 89;
export declare const HI_CLICK_PITCH = 90;
export declare const LO_CLICK_CLASS = 9;
export declare const HI_CLICK_CLASS = 10;
