export const MIN_VRAM = 50;
export const LOWEST_LD = -120;
export const CROSSFADE_DURATION = 1;
export const OUTPUT_SAMPLE_RATE = 48000;
export const LD_CONF_REDUCTION = -25.0;
export const CONF_SMOOTH_SIZE = 100;
export const PITCHES_HOP = 8192;
export const CONF_THRESHOLD = 0.7;
//# sourceMappingURL=constants.js.map